//
//
//  Extension: REST Client
//
//

GET {{baseURL}}/ HTTP/1.1

###

POST {{baseURL}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Example",
  "email": "example@gmail.com",
  "cpf": "25252525252",
  "passwd": "example123"
}

###
# @name login

POST {{baseURL}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "example@gmail.com",
  "cpf": "25252525252",
  "passwd": "example123"
}

###

GET {{baseURL}}/user HTTP/1.1
Cookie: {{cookie}}

###

PUT {{baseURL}}/user/update HTTP/1.1
Content-Type: application/json
Cookie: {{cookie}}

{
  "name": "Test"
}

###

DELETE {{baseURL}}/user/delete HTTP/1.1
Cookie: {{cookie}}

###

@baseURL = http://127.0.0.1:8000

@cookie = {{login.response.headers.set-cookie}}
